server.document-root = "/var/www/adminer"
server.port = 8080
server.bind = "0.0.0.0"
server.username = "www-data"
server.groupname = "www-data"
server.pid-file = "/run/lighttpd/lighttpd.pid"
server.errorlog = "/dev/stderr"
accesslog.filename = "/dev/stdout"
server.modules = ( "mod_accesslog", "mod_cgi", "mod_setenv" )
index-file.names = ( "index.php" )
cgi.assign = ( ".php" => "/usr/bin/php-cgi" )
mimetype.assign = ( ".php" => "text/html; charset=utf-8" )
setenv.add-response-header = (
  "X-Content-Type-Options" => "nosniff",
  "X-Frame-Options" => "DENY",
  "Referrer-Policy" => "no-referrer"
)
