server.document-root = "/var/www/static"
server.port = 8080
server.bind = "0.0.0.0"
server.username = "www-data"
server.groupname = "www-data"
server.pid-file = "/run/lighttpd/lighttpd.pid"
server.errorlog = "/dev/stderr"
accesslog.filename = "/dev/stdout"
server.modules = ( "mod_accesslog", "mod_setenv" )
index-file.names = ( "index.html" )
mimetype.assign = (
  ".html" => "text/html; charset=utf-8",
  ".css" => "text/css",
  ".svg" => "image/svg+xml"
)
setenv.add-response-header = (
  "X-Content-Type-Options" => "nosniff",
  "X-Frame-Options" => "DENY"
)
